### PR TITLE
compile just using cython and add github-ci

### PR DESCRIPTION
**Pull request by tfmoraes**
Hi,

I work with @vhosouza @rmatsuda on InVesalius. To ease the process of creating wheels for various versions of Python and platforms I created this PR. This PR create a new action to create wheels using the Github CI. It uses [Cibuildwheel](https://github.com/pypa/cibuildwheel) and creates wheels to Windows, Linux and MacOS (x86_64 and ARM64) from Python 3.8 to 3.11. For now it only creates the wheels. You can make it publish the wheels to Pypi automatically using Github CI [this way](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/#github-actions). To upload the wheels to Pypi by yourself you need to download the artifacts (in the GitHub tab Action, click in the last workflow run completed and look for the artifact in the bottom of the page) and use twine.

With PR you don't need Cmake to create the Python wheels. Just enter on `src/python` and run `python setup.py bdist_wheel`. It compiles all codes using the Python and Cython machinery.

I did some modifications to compile on clang on MacOs:

- Use of `std::vector` of `std::threads` on on `src/config/multithreader.cpp` .
- On `src/math/doRandomThings.cpp` I added condition to not use the assembly code
- Changed the extensions of the C codes to CPP

### CODE REVIEW

**Comment by baranaydogan** [comment]
Hi! Thanks a lot for the contribution! This is a great idea! Let's try it! Unfortunately, I don't have the time to compile and share the binaries right now. But we can merge the code.

**Review by baranaydogan — APPROVED** [review]

**Comment by baranaydogan** [comment]
Thanks for the pull request again. Most people actually only use command line binaries and not the Python wheels. So there is need to update the binaries provided in the release. For that there is need to compile binaries for Linux, Windows and Mac. For that one thing that needs to be done is to modify the [CMakeLists.txt](https://github.com/dmritrekker/trekker/blob/29ea2d87ef1485655d2e205520f6cbf381ed7280/CMakeLists.txt) for Mac actually. But I haven't had the time to look into that.

**Comment by baranaydogan** [comment]
Hi @tfmoraes. It is now there in https://pypi.org/project/Trekker/. pip install worked at least in the few Linux computer that I tested. Hopefully it works in Win and Mac too. We can fix if there are issues. I have to say that it is muuch better this way :smile: Thanks a lot again for contributing!

**Comment by tfmoraes** [comment]
Hi @baranaydogan it worked for me on MacOS with Apple Silicon. Thanks!

**Comment by vhosouza** [comment]
This is excellent! Thanks guys. @baranaydogan it worked for me as well in Windows 11

**Comment by baranaydogan** [comment]
Lovely! Thanks  again to both of you for helping out!

**Comment by AndrewZh** [comment]
Hi all, for me it complained a lot about char * being assigned string literals. As well as printing char * using fprintf (which was inconsistent actually, neighbour lines would have different setup). 
I have now also successfully built on Mac with M1, I have updates in my fork

**Pull request merged**
